version: '3.8'

services:
  app:
    build: Investment
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Investment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: Investment
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8081:8080"
